### ISSUE TITLE
Cant add delay to gif

### ISSUE THREAD

**Issue by KevinL0206** [cloudinary/cloudinary_kotlin#101]
![Screenshot 2024-05-30 at 17 31 39](https://github.com/cloudinary/cloudinary_kotlin/assets/90875029/f5a940cf-8272-4caa-8033-013b780d3073)

Trying to create a gif from 4 images, but I want to add a delay between the frames. How do i fix this error?

**Comment by rnamba-cloudinary** [comment]
Hey Kevin,

Not sure this is an issue with the Kotlin SDK, seems more like support is needed here. Would you be able to submit a ticket to our support team at support@cloudinary.com? Please include the full truncated `..values` value in the above screenshot.
