### ISSUE TITLE
AuthToken.kt various warnings

### ISSUE THREAD

**Issue by TomerPacific** [cloudinary/cloudinary_kotlin#110]
When inspecting the **AuthToken.kt** file, there are 7 warnings there:

1. Private property name 'UNSAFE_URL_CHARS_PATTERN' should not contain underscores in the middle or the end (line 24)
2. Unchecked cast: Any? to ArrayList<String> (line 47)
3. 'acl: String?' is deprecated. This parameter will be removed in the next major version, use acls instead (lines 75, 76, 82, 124 and 139)

Relates to #107

**Comment by wissam-khalili** [comment]
@adimiz1 - Can you please review this one?
Thanks!

**Comment by TomerPacific** [comment]
@wissam-khalili - Since the deprecation warning is internal, do we want to remove the parameter?

**Comment by wissam-khalili** [comment]
@adimiz1  - Can you review @TomerPacific  question?

**Comment by TomerPacific** [comment]
@adimiz1 ?
