### ISSUE TITLE
Support raw transformations

### ISSUE THREAD

**Issue by farmerbb** [cloudinary/cloudinary_kotlin#45]
I greatly appreciate the type-safety this SDK provides when working with Cloudinary.  However, for certain images, my use case requires the ability to add a set of predefined raw transformations at runtime, as provided by our backend.

The iOS SDK contains a `rawTransformation` function, as documented here: https://cloudinary.com/documentation/ios_image_manipulation#add_transformations

Requesting the addition of a similar function for the Kotlin SDK.  As a workaround I am needing to manipulate the final generated URL which is not ideal.

**Comment by farmerbb** [comment]
Just saw that the Kotlin SDK has a `RawAction` that can be added to the `Image.Builder`.  This should work for my use case.

**Comment by patrick-tolosa** [comment]
@farmerbb great you found the RawAction! 
We intentionally kept it open for use cases such as these.
